---
title: "R Notebook"
output: html_notebook
---

UMAP only MP 

```{r library}

library(Seurat)
#library(leiden)
#library(leidenAlg)
library(ggplot2)
#library(sctransform)
#library(scDblFinder)
#library(SingleCellExperiment)
#library("viridis")
#library(knitr)
library(dplyr)
#library(readxl)
#library(SingleR)
#library(celldex)
library(ggplot2)
library(patchwork)
#library ("harmony")
library (hdf5r)
library(pheatmap)
```
# Load objects

```{r load objects}
GSE_integrated  = readRDS ( ".../results/GSE_integrated") #SCTransform, 3 datasets
GSE_merge_annotated = readRDS (".../Datasets/Merged/GSE_merge_annotated")
GSE_MP = readRDS (".../Datasets/DEA/GSE_MP")
GSE_MP_SCT = readRDS ( ".../Datasets/GSE_MP_SCT")
GSE_MP_pos = readRDS("...Datasets/GSE_MP_pos")
saveRDS(all.markers,".../Datasets/all.markers_MPpos") # all markers for TLS+ MP (5 clusters)
```

# Subsetting MP

```{r}
# subsetting MP

GSE_integrated$ct_ann_GSE344_10kSingleR = GSE_merge_annotated@meta.data[["ct_ann_GSE344_10kSingleR"]]
cell_sub = c("MAMs:APOE+", "MAMs:S100A8+")

GSE_list = list()
GSE_sub = subset (GSE_integrated, subset = ct_ann_GSE344_10kSingleR == "MAMs:APOE+")  #initalize GSE_sub, otherwise wont work
GSE_sub2 = subset (GSE_integrated, subset = ct_ann_GSE344_10kSingleR == "MAMs:S100A8+")  #initalize GSE_sub, otherwise wont work
GSE_sub = merge(GSE_sub,GSE_sub2)
# Join layers
GSE_sub@assays[["RNA"]] = JoinLayers(GSE_sub@assays[["RNA"]]) #merge layers

#adding annotation
GSE_sub$TLS_patient = GSE_MP@meta.data[["TLS_patient"]]


```

# Clustering wo integration

```{r Clustering without integration}
#In DEA_UMAP_cluster

```

```{r}
GSE_MP_SCT = readRDS ( ".../Datasets/GSE_MP_SCT")

############################### Clustering with automated var genes

GSE_MP_SCT = RunPCA (GSE_MP_SCT) 
GSE_MP_SCT <- RunUMAP(GSE_MP_SCT, dims = 1:40) 

#saving the plot
png (".../Output/DEA/UMAP_cluster_Anno.png",width = 800, height = 600)
DimPlot(GSE_MP_SCT, reduction = "umap", group.by = c("ct_ann_GSE344_10kSingleR")) #ct_ann_GSE344_10kSingleR
dev.off()
png (".../Output/DEA/UMAP_cluster_cancertypes.png",width = 800, height = 600)
DimPlot(GSE_MP_SCT, reduction = "umap", group.by = c("cancer_types")) #ct_ann_GSE344_10kSingleR
dev.off()
png (".../Output/DEA/UMAP_cluster_TLS.png",width = 800, height = 600)
DimPlot(GSE_MP_SCT, reduction = "umap", group.by = c("TLS_patient"))
dev.off()
png (".../Output/DEA/UMAP_cluster_datasets.png",width = 800, height = 600)
DimPlot(GSE_MP_SCT, reduction = "umap", group.by = c("dataset_ID"))
dev.off()
############################### Clustering with DEA genes
GSE_MP_SCT@assays[["SCT"]]@var.features = head(rownames(MP_markers_NC),3000) 
GSE_MP_SCT = RunPCA (GSE_MP_SCT) 
GSE_MP_SCT <- RunUMAP(GSE_MP_SCT, dims = 1:40) 

#saving the plot
png (".../Output/DEA/UMAP_cluster_Anno_DEA.png",width = 800, height = 600)
DimPlot(GSE_MP_SCT, reduction = "umap", group.by = c("ct_ann_GSE344_10kSingleR")) #ct_ann_GSE344_10kSingleR
dev.off()
png (".../Output/DEA/UMAP_cluster_cancertypes_DEA.png",width = 800, height = 600)
DimPlot(GSE_MP_SCT, reduction = "umap", group.by = c("cancer_types")) #ct_ann_GSE344_10kSingleR
dev.off()
png (".../Output/DEA/UMAP_cluster_TLS_DEA.png",width = 800, height = 600)
DimPlot(GSE_MP_SCT, reduction = "umap", group.by = c("TLS_patient"))
dev.off()
png (".../Output/DEA/UMAP_cluster_datasets_DEA.png",width = 800, height = 600)
DimPlot(GSE_MP_SCT, reduction = "umap", group.by = c("dataset_ID"))
dev.off()
png (".../Output/DEA/UMAP_cluster_datasets.png",width = 800, height = 600)
DimPlot(GSE_MP_SCT, reduction = "umap", group.by = c("dataset_ID"))
dev.off()
```
# Integration
```{r Integration}
# split layers 
# integrate datasets
GSE_MP_SCT <- IntegrateLayers(object = GSE_MP_SCT, method = CCAIntegration, normalization.method = "SCT", verbose = F)
GSE_MP_SCT <- FindNeighbors(GSE_MP_SCT, reduction = "integrated.dr", dims = 1:40)
GSE_MP_SCT <- FindClusters(GSE_MP_SCT, resolution = 0.1) #try different resolution 

GSE_MP_SCT <- RunUMAP(GSE_MP_SCT, dims = 1:40, reduction = "integrated.dr")

GSE_MP_SCT$"MAMs phenotypes" = GSE_MP_SCT@meta.data[["ct_ann_GSE344_10kSingleR"]]
NAs = GSE_MP_SCT@meta.data[["TLS_patient"]] == "NA"
GSE_MP_SCT@meta.data[["TLS_patient"]] [NAs]=  "TLS negative"
GSE_MP_SCT$"TLS patients" = GSE_MP_SCT$TLS_patient
library(RColorBrewer)

# Define the alphabet color palette (if not predefined)
purple_palette <- c("#58508d","#d4b200")
navy_palette = c("#58508d","#d4b200")
png (".../Output/new_UMAP/UMAP_cluster0.1.png",width = 650, height = 450)
DimPlot(GSE_MP_SCT, reduction = "umap", group.by = c("SCT_snn_res.0.1"))
dev.off()

```

# Clusters and TLS+ 
## Res 0.1
```{r}

## number of MP cells in TLS+ and TLS- samples 
no_pos = sum(GSE_MP_SCT@meta.data[["TLS_patient"]] == "TLS positive") #984
no_neg = 7486-984 #6502

##
c0 = GSE_MP_SCT[,GSE_MP_SCT@meta.data[["SCT_snn_res.0.1"]] == 0]
sum(c0@meta.data[["TLS_patient"]] == "TLS positive")/no_pos #472 0.4796748
(length(Cells(c0)) -  sum(c0@meta.data[["TLS_patient"]] == "TLS positive"))/no_neg #2974 0.4573977

c1 = GSE_MP_SCT[,GSE_MP_SCT@meta.data[["SCT_snn_res.0.1"]] == 1]
sum(c1@meta.data[["TLS_patient"]] == "TLS positive")/no_pos #450 0.4573171
(length(Cells(c1)) -  sum(c1@meta.data[["TLS_patient"]] == "TLS positive"))/no_neg #1419 0.2182405

c2 = GSE_MP_SCT[,GSE_MP_SCT@meta.data[["SCT_snn_res.0.1"]] == 2]
sum(c2@meta.data[["TLS_patient"]] == "TLS positive")/no_pos #41 0.04166667
(length(Cells(c2)) -  sum(c2@meta.data[["TLS_patient"]] == "TLS positive"))/no_neg #1138 0.1750231

c3 = GSE_MP_SCT[,GSE_MP_SCT@meta.data[["SCT_snn_res.0.1"]] == 3]
sum(c3@meta.data[["TLS_patient"]] == "TLS positive")/no_pos #12 0.01219512
(length(Cells(c3)) -  sum(c3@meta.data[["TLS_patient"]] == "TLS positive"))/no_neg #740 0.1138111

c4 = GSE_MP_SCT[,GSE_MP_SCT@meta.data[["SCT_snn_res.0.1"]] == 4]
sum(c4@meta.data[["TLS_patient"]] == "TLS positive")/no_pos #0
(length(Cells(c4)) -  sum(c4@meta.data[["TLS_patient"]] == "TLS positive"))/no_neg #124 0.01907106

c5 = GSE_MP_SCT[,GSE_MP_SCT@meta.data[["SCT_snn_res.0.1"]] == 5]
sum(c5@meta.data[["TLS_patient"]] == "TLS positive")/no_pos #9 0.009146341
(length(Cells(c5)) -  sum(c5@meta.data[["TLS_patient"]] == "TLS positive"))/no_neg #107 0.016456

## Calculating %

c0_per = (sum(c0@meta.data[["TLS_patient"]] == "TLS positive")/no_pos)*100



## TLS+ MP is enriched in both clusters -> smaller resolution

c0 = GSE_MP_SCT[,GSE_MP_SCT@meta.data[["SCT_snn_res.0.1"]] == 0]
sum(c0@meta.data[["TLS_patient"]] == "TLS positive") #472
c1 = GSE_MP_SCT[,GSE_MP_SCT@meta.data[["SCT_snn_res.0.1"]] == 1]
sum(c1@meta.data[["TLS_patient"]] == "TLS positive") #450


```
## S1 and APOE 

```{r S100A8 and APOE}

## number of MP cells in TLS+ and TLS- samples 
pos_obj = GSE_MP_SCT[,GSE_MP_SCT@meta.data[["TLS_patient"]] == "TLS positive"] 
neg_obj = GSE_MP_SCT[,GSE_MP_SCT@meta.data[["TLS_patient"]] != "TLS positive"] 


# % APOE 
sum(neg_obj@meta.data[["ct_ann_GSE344_10kSingleR"]] == "MAMs:APOE+")/length(Cells(neg_obj)) #0.6171947

sum(pos_obj@meta.data[["ct_ann_GSE344_10kSingleR"]] == "MAMs:APOE+")/length(Cells(pos_obj)) #0.3119919

## % S100A8
sum(pos_obj@meta.data[["ct_ann_GSE344_10kSingleR"]] == "MAMs:S100A8+")/length(Cells(pos_obj)) #0.6880081

sum(neg_obj@meta.data[["ct_ann_GSE344_10kSingleR"]] == "MAMs:S100A8+")/length(Cells(neg_obj)) #0.3828053

### Barplot 

# Sample data
TLS_pos <- data.frame(
  category = c("MAMs:S100A8+", "MAMs:APOE+"),
  counts = c(68.8,31.2)
)

# Creating the bar plot
p1 = ggplot(TLS_pos, aes(x = category, y = counts, fill = category)) +
  geom_bar(stat = "identity") +
  theme_minimal() +
  labs(title = "TLS positive samples", x = "MAMs phenotypes", y = "Percentage (%)")

# Sample data
TLS_neg <- data.frame(
  category = c("MAMs:S100A8+", "MAMs:APOE+"),
  counts = c(38.3,61.7)
)

# Creating the bar plot


combined_data <- bind_rows(
  TLS_pos %>% mutate(dataset = "TLS positive samples"),
  TLS_neg %>% mutate(dataset = "TLS negative samples"))

# Plot with facet_wrap
ggplot(combined_data, aes(x = category, y = counts, fill = category)) +
  geom_bar(stat = "identity", position = "stack") +
  facet_wrap(~ dataset,nrow =1) + #nrow =2
  scale_fill_manual(values = c("MAMs:S100A8+" = "#d4b200", "MAMs:APOE+" = "#58508d")) +
  labs(title = "MAMs phenotypes", x = "", y = "Percentage (%)") +
  theme_minimal()
# 400x700("#58508d","#d4b200")
```

## Heatmap APOE and S100A8 

```{r}
Idents(GSE_MP_SCT) <- GSE_MP_SCT$ct_ann_GSE344_10kSingleR
GSE_MP_SCT = PrepSCTFindMarkers(GSE_MP_SCT)
MP.markers_all <- FindAllMarkers(GSE_MP_SCT)
MP.markers_all %>%
    group_by(cluster) %>%
    dplyr::filter(avg_log2FC > 0.5)

MP.markers_all %>%
    group_by(cluster) %>%
    dplyr::filter(avg_log2FC > 1) %>%
  #  arrange(desc(avg_log2FC)) %>% 
    slice_head(n = 20) %>%
    ungroup() -> top50
png (".../Output/new_UMAP/Heatmap_TLSpos.png",width = 800, height = 600)
DoHeatmap(GSE_MP_SCT, features = top50$gene) + NoLegend() 
dev.off
```

## Res 0.05 
```{r}
c0 = GSE_MP_SCT[,GSE_MP_SCT@meta.data[["SCT_snn_res.0.05"]] == 0]
sum(c0@meta.data[["TLS_patient"]] == "TLS positive")/no_pos #0.9369919
(length(Cells(c0)) -  sum(c0@meta.data[["TLS_patient"]] == "TLS positive"))/no_neg # 0.6734851

c1 = GSE_MP_SCT[,GSE_MP_SCT@meta.data[["SCT_snn_res.0.05"]] == 1]
sum(c1@meta.data[["TLS_patient"]] == "TLS positive")/no_pos #0.04166667
(length(Cells(c1)) -  sum(c1@meta.data[["TLS_patient"]] == "TLS positive"))/no_neg # 0.1962473

c2 = GSE_MP_SCT[,GSE_MP_SCT@meta.data[["SCT_snn_res.0.05"]] == 2]
sum(c2@meta.data[["TLS_patient"]] == "TLS positive")/no_pos #0.01219512
(length(Cells(c2)) -  sum(c2@meta.data[["TLS_patient"]] == "TLS positive"))/no_neg # 0.1138111

c3 = GSE_MP_SCT[,GSE_MP_SCT@meta.data[["SCT_snn_res.0.05"]] == 3]
sum(c3@meta.data[["TLS_patient"]] == "TLS positive")/no_pos #0.009146341
(length(Cells(c3)) -  sum(c3@meta.data[["TLS_patient"]] == "TLS positive"))/no_neg # 0.01645647


```
```{r}
Idents(GSE_MP_SCT) = GSE_MP_SCT@meta.data[["SCT_snn_res.0.05"]]
GSE_MP_SCT = PrepSCTFindMarkers(GSE_MP_SCT)
MP.markers_all <- FindAllMarkers(GSE_MP_SCT)
MP.markers_all %>%
    group_by(cluster) %>%
    dplyr::filter(avg_log2FC > 0.5)
```


# Investigating each clusters of MP UMAP


```{r}
# Run integration and clustering again (above Abschnitt)
DimPlot(GSE_MP_SCT, reduction = "umap", group.by = c("MAMs phenotypes"))
DimPlot(GSE_MP_SCT, reduction = "umap", group.by = c("seurat_clusters")) #with 0.1 resolution: 5 clusters

```


```{r Find markers for each clusters}
#

PrepSCTFindMarkers(GSE_MP_SCT)
MP.markers <- FindAllMarkers(GSE_MP_SCT)
MP.markers %>%
    group_by(cluster) %>%
    dplyr::filter(avg_log2FC > 0.5)

```

# MP in TLS+
```{r Subsettins TLS +/-}
GSE_MP_pos = subset(x = GSE_MP_SCT, subset = TLS_patient == "TLS positive") #984 cells 
GSE_MP_neg = subset(x = GSE_MP_SCT, subset = TLS_patient == c("TLS negative"))#1057 cells, 
GSE_MP_NA = subset(x = GSE_MP_SCT, subset = TLS_patient == c("NA"))#5445 cells, 
GSE_MP_neg = merge(GSE_MP_neg,GSE_MP_NA)
```
## UMAP

```{r Integrate and clustering}
GSE_MP_pos <- IntegrateLayers(object = GSE_MP_pos, method = CCAIntegration, normalization.method = "SCT", verbose = F,k.weight =80)
GSE_MP_pos <- FindNeighbors(GSE_MP_pos, reduction = "integrated.dr", dims = 1:50)
GSE_MP_pos <- FindClusters(GSE_MP_pos, resolution = 0.3) #try different resolution 
GSE_MP_pos <- RunUMAP(GSE_MP_pos, dims = 1:50, reduction = "integrated.dr")

# change name to Macro-0 and so on
cluster_labels = GSE_MP_pos@meta.data[["seurat_clusters"]] 
cluster_names <- paste("Macro-", cluster_labels, sep = "")
GSE_MP_pos@meta.data[["seurat_clusters"]] = cluster_names
```

```{r Plotting}
DimPlot(GSE_MP_pos, reduction = "umap", group.by = c("seurat_clusters")) #with 0.1 resolution: 5 clusters
DimPlot(GSE_MP_pos, reduction = "umap", group.by = c("seurat_clusters")) #with 0.1 resolution: 5 clusters
png (".../Output/new_UMAP/TLSpos.png",width = 500, height = 400)
DimPlot(GSE_MP_pos, reduction = "umap", group.by = c("seurat_clusters"),pt.size = 0.5) #with 0.1 resolution: 5 clusters
dev.off()
```

## FindMarkers
```{r Markers in TLS positive}
Idents(GSE_MP_pos) = GSE_MP_pos@meta.data[["SCT_snn_res.0.3"]]
GSE_MP_pos = PrepSCTFindMarkers(GSE_MP_pos)

all.markers <- FindAllMarkers(GSE_MP_pos, only.pos = F,test.use = "MAST")
all.markers %>%
    group_by(cluster) %>%
    dplyr::filter(avg_log2FC > 1) %>%
    dplyr::filter(p_val_adj > 0.05)

cluster0 = all.markers [all.markers$cluster == 0,]
cluster0 = cluster0[(cluster0$avg_log2FC > 0.5 & cluster0$p_val_adj < 0.05) | (cluster0$avg_log2FC  & cluster0$p_val_adj < 0.05),]


cluster1 = all.markers [all.markers$cluster == 1,]
cluster1 = cluster1[(cluster1$avg_log2FC > 0.5 & cluster1$p_val_adj < 0.05) | (cluster1$avg_log2FC  & cluster1$p_val_adj < 0.05),]

cluster2 = all.markers [all.markers$cluster == 2,]
cluster2 = cluster2[(cluster2$avg_log2FC > 0.5 & cluster2$p_val_adj < 0.05) | (cluster2$avg_log2FC  & cluster2$p_val_adj < 0.05),]


cluster3 = all.markers [all.markers$cluster == 3,]
cluster3 = cluster3[(cluster3$avg_log2FC > 0.5 & cluster3$p_val_adj < 0.05) | (cluster3$avg_log2FC  & cluster3$p_val_adj < 0.05),] ######## chnage p adj to pval


cluster4 = all.markers [all.markers$cluster == 4,]
cluster4 = cluster4[(cluster4$avg_log2FC > 0.5 & cluster4$p_val_adj < 0.05) | (cluster4$avg_log2FC  & cluster4$p_val_adj < 0.05),]
```


```{r heatmap}
all.markers %>%
    group_by(cluster) %>%
    dplyr::filter(avg_log2FC > 1) %>%
    slice_head(n = 15) %>%
    ungroup() -> top15
png (".../Output/new_UMAP/Heatmap_TLSpos.png",width = 800, height = 600)
DoHeatmap(GSE_MP_pos, features = top15$gene) + NoLegend() #Warning: The following features were omitted as they were not found in the scale.data slot for the SCT assay: PAGE2, CTAG2, PAGE5, PAGE2B, SFTPA2, ELANE, SFTPB, IGLV3-19, IGLV3-1
dev.off
```
## GSEA
```{r GSEA}

library(clusterProfiler)
library(enrichplot)
# we use ggplot2 to add x axis labels (ex: ridgeplot)
library(ggplot2)
library(dplyr)


# SET THE DESIRED ORGANISM HERE
organism = "org.Hs.eg.db" #homo sapiens
BiocManager::install(organism, character.only = TRUE)
library(organism, character.only = TRUE)
```

```{r}
# we want log2 fc 

cluster0_markers <- cluster0$avg_log2FC
names(cluster0_markers) <- cluster0$gene #250 genes
# sort the list in decreasing order (required for clusterProfiler)
cluster0_markers = sort(cluster0_markers, decreasing = TRUE)


cluster1_markers <- cluster1$avg_log2FC
names(cluster1_markers) <- cluster1$gene #769 genes
# sort the list in decreasing order (required for clusterProfiler)
cluster1_markers = sort(cluster1_markers, decreasing = TRUE)

cluster2_markers <- cluster2$avg_log2FC
names(cluster2_markers) <- cluster2$gene #592 genes
# sort the list in decreasing order (required for clusterProfiler)
cluster2_markers = sort(cluster2_markers, decreasing = TRUE)

cluster3_markers <- cluster3$avg_log2FC
names(cluster3_markers) <- cluster3$gene #249 genes
# sort the list in decreasing order (required for clusterProfiler)
cluster3_markers = sort(cluster3_markers, decreasing = TRUE)

cluster4_markers <- cluster4$avg_log2FC
names(cluster4_markers) <- cluster4$gene #584 genes
# sort the list in decreasing order (required for clusterProfiler)
cluster4_markers = sort(cluster4_markers, decreasing = TRUE)


```


```{r}

gse_0 <- gseGO(geneList=cluster0_markers, 
             ont ="CC", 
             keyType = "SYMBOL", 
          #   nPerm = 10000, # remove nPerm bc Warning: You are trying to run fgseaSimple. It is recommended to use fgseaMultilevel. To run fgseaMultilevel, you need to remove the nperm argument in the fgsea function call.no term enriched under specific pvalueCutoff...
             minGSSize = 3,  #(gene sets with lower than this many genes in your dataset will be ignored).
             maxGSSize = 1500, # (gene sets with greater than this many genes in your dataset will be ignored).
             pvalueCutoff = 0.05, 
             verbose = TRUE, 
             OrgDb = organism,
             pAdjustMethod = "none")

gse_1 <- gseGO(geneList=cluster1_markers, 
             ont ="MF", 
             keyType = "SYMBOL", 
          #   nPerm = 10000, # remove nPerm bc Warning: You are trying to run fgseaSimple. It is recommended to use fgseaMultilevel. To run fgseaMultilevel, you need to remove the nperm argument in the fgsea function call.no term enriched under specific pvalueCutoff...
             minGSSize = 3,  #(gene sets with lower than this many genes in your dataset will be ignored).
             maxGSSize = 1500, # (gene sets with greater than this many genes in your dataset will be ignored).
             pvalueCutoff = 0.05, 
             verbose = TRUE, 
             OrgDb = organism, 
             pAdjustMethod = "none")


gse_2 <- gseGO(geneList=cluster2_markers, 
             ont ="MF", 
             keyType = "SYMBOL", 
          #   nPerm = 10000, # remove nPerm bc Warning: You are trying to run fgseaSimple. It is recommended to use fgseaMultilevel. To run fgseaMultilevel, you need to remove the nperm argument in the fgsea function call.no term enriched under specific pvalueCutoff...
             minGSSize = 3,  #(gene sets with lower than this many genes in your dataset will be ignored).
             maxGSSize = 1500, # (gene sets with greater than this many genes in your dataset will be ignored).
             pvalueCutoff = 0.05, 
             verbose = TRUE, 
             OrgDb = organism, 
             pAdjustMethod = "none")

gse_3 <- gseGO(geneList=cluster3_markers, 
             ont ="BP", 
             keyType = "SYMBOL", 
          #   nPerm = 10000, # remove nPerm bc Warning: You are trying to run fgseaSimple. It is recommended to use fgseaMultilevel. To run fgseaMultilevel, you need to remove the nperm argument in the fgsea function call.no term enriched under specific pvalueCutoff...
             minGSSize = 3,  #(gene sets with lower than this many genes in your dataset will be ignored).
             maxGSSize = 1500, # (gene sets with greater than this many genes in your dataset will be ignored).
             pvalueCutoff = 0.05, 
             verbose = TRUE, 
             OrgDb = organism, 
             pAdjustMethod = "none")

gse_3_MF = data.frame(gse_3@result[["Description"]],gse_3@result[["core_enrichment"]])

gse_3_BP = data.frame(gse_3@result[["Description"]],gse_3@result[["core_enrichment"]])
gse_4 <- gseGO(geneList=cluster4_markers, 
             ont ="BP", 
             keyType = "SYMBOL", 
          #   nPerm = 10000, # remove nPerm bc Warning: You are trying to run fgseaSimple. It is recommended to use fgseaMultilevel. To run fgseaMultilevel, you need to remove the nperm argument in the fgsea function call.no term enriched under specific pvalueCutoff...
             minGSSize = 3,  #(gene sets with lower than this many genes in your dataset will be ignored).
             maxGSSize = 1500, # (gene sets with greater than this many genes in your dataset will be ignored).
             pvalueCutoff = 0.05, 
             verbose = TRUE, 
             OrgDb = organism, 
             pAdjustMethod = "none")

gse_4_MF = data.frame(gse_4@result[["Description"]],gse_4@result[["core_enrichment"]])

gse_4_BP = data.frame(gse_4@result[["Description"]],gse_4@result[["core_enrichment"]])
```

```{r}
require(DOSE)
png(".../Output/GSEA/cluster0_CC.png", width = 500, height = 600)
dotplot(gse_0, showCategory=5, split=".sign") + facet_grid(.~.sign)
dev.off()
png(".../GSEA/cluster1_CC.png", width = 500, height = 600)
dotplot(gse_1, showCategory=5, split=".sign") + facet_grid(.~.sign)
dev.off()
png(".../GSEA/cluster2_CC.png", width = 500, height = 600)
dotplot(gse_2, showCategory=5, split=".sign") + facet_grid(.~.sign)
dev.off()
png(".../Output/GSEA/cluster3_MF.png", width = 500, height = 600)
dotplot(gse_3, showCategory=5, split=".sign") + facet_grid(.~.sign)
dev.off()
png(".../Output/GSEA/cluster4_MF.png", width = 550, height = 650)
dotplot(gse_4, showCategory=5, split=".sign") + facet_grid(.~.sign)
dev.off()

```
## Cluster 2/3 and ST result

```{r}
cluster3_markers = cluster3$gene [cluster3$avg_log2FC > 0.5]
cluster3_markers_down = cluster3$gene [cluster3$avg_log2FC < -0.5]

gene_up_marker = gene_counts_df$Gene [gene_counts_df$Count > 6]

gene_down_marker = gene_counts_df_down$Gene [gene_counts_df_down$Count > 6]

cluster3_markers[cluster3_markers %in% gene_up_marker] #" "LYZ"   "CYBB"  "PTPRC" "LCP1"  "RAC2" 
#RAC2: pro tumor, M2, but maybe in the context of TLS? 
cluster3_markers_down[cluster3_markers_down %in% gene_down_marker]#11 "FTH1" "SPP1" "MIF"  "MGLL" "CAV1"

cluster2_markers = cluster2$gene [cluster2$avg_log2FC > 0.5]
cluster2_markers_down = cluster2$gene [cluster2$avg_log2FC < -0.5]

cluster2_markers[cluster2_markers %in% gene_up_marker] #0
cluster2_markers_down[cluster2_markers_down %in% gene_down_marker] # "LGALS3BP" "CD81"     "SPP1"   

##### BUT: VEGFA, PLIN2, FTH1 up in 2 

###########''''CLusert1 
cluster1_markers = cluster1$gene [cluster1$avg_log2FC > 0.5]
cluster1_markers_down = cluster1$gene [cluster1$avg_log2FC < -0.5]

cluster1_markers[cluster1_markers %in% gene_up_marker] # 0
cluster1_markers_down[cluster1_markers_down %in% gene_down_marker] #  "VIM"   "PLIN2" "ICAM1" "ANPEP" "FTH1"  "TXN"  

```

