---
title: "Spatial_Deconvolution"
output: html_document
date: "2024-06-11"
---

# Deconvolution script, using immunedeconv
https://omnideconv.org/immunedeconv/articles/immunedeconv.html#introduction 
Installation of the pakage: https://www.rdocumentation.org/packages/immunedeconv/versions/2.0.3

```{r load object}
saveRDS (c3_obj,".../Datasets/Spatial_transcriptomics/c3_obj" )

```

```{r library}
library(Seurat)
library(SeuratData)
library(ggplot2)
library(patchwork)
library(dplyr)
library(Matrix)
```

```{r TPM normalize}

c3_count = c3_obj@assays[["Spatial"]]@layers[["counts"]] 
c3_count <- as.matrix(c3_count)  # Ensure counts is a matrix
total_counts_per_cell <- colSums(c3_count)

#calculating TPM normalized
c3_tpm <- t(t(c3_count) / total_counts_per_cell) * 1e6

 DefaultAssay(c3_obj) <- "Spatial"
length (Features(c3_obj))# 17943
rownames (c3_tpm) = Features(c3_obj)
```
-------------------------------------------- immunedeconv
remotes::install_github("icbi-lab/immunedeconv")
library ("immunedeconv")
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace ‘purrr’ 1.0.1 is being loaded, but >= 1.0.2 is required
Calls: <Anonymous> ... namespaceImportFrom -> asNamespace -> loadNamespace
Execution halted
ERROR: lazy loading failed for package ‘immunedeconv’

-------------------------------------------- MCP-counter
MCP-counter uses its transcriptomic markers (TM) curated from 81 public datasets to estimate fibroblasts, endothelial cells, and eight immune cell types.
res_mcp = as.data.frame(deconvolute(df, "mcp_counter"))

-------------------------------------------- 
```{r}
BiocManager::install("STdeconvolve")
library (STdeconvolve) 


library(devtools)
install_github("ebecht/MCPcounter",ref="master", subdir="Source")
library(MCPcounter)
c3_mcp = (deconvolute(c3_tpm, "mcp_counter"))
res_xcell <- xCellAnalysis(c3_tpm)
```



```{r}
BiocManager::install("STdeconvolve")
library (STdeconvolve) 
library(STdeconvolve)
## load built in data



#data(mOB)
pos = coords #pos <- mOB$pos #coord from c3_obj
cd = c3_obj@assays[["Spatial"]]@layers[["counts"]] #cd <- mOB$counts #count
annot = c3_obj@meta.data[["TLS_anno"]] #annot <- mOB$annot #TLS?? 
## remove pixels with too few genes
#counts <- cleanCounts(cd, min.lib.size = 100)
## feature select for genes
corpus <- restrictCorpus(counts, removeAbove=1.0, removeBelow = 0.05)
## choose optimal number of cell-types
ldas <- fitLDA(t(as.matrix(corpus)), Ks = seq(2,3, by = 1))
## get best model results
optLDA <- optimalModel(models = ldas, opt = "min")
## extract deconvolved cell-type proportions (theta) and transcriptional profiles (beta)
results <- getBetaTheta(optLDA, perc.filt = 0.05, betaScale = 1000)
deconProp <- results$theta
deconGexp <- results$beta
## visualize deconvolved cell-type proportions
vizAllTopics(deconProp, pos,
             groups = annot, 
             group_cols = rainbow(length(levels(annot))),
             r=0.4)	 
```



