---
title: "R Notebook"
output: html_notebook
---

Spatial integration/deconvolution using sc reference 

```{r}
library(Seurat)
library(SeuratData)
library(ggplot2)
library(patchwork)
library(dplyr)
library(readxl)
```

```{r load objects}
c3_obj = readRDS("/omics/groups/OE0436/data/Linh/Datasets/Spatial_transcriptomics/c3_obj")


```

# Single cell reference

```{r Importing sc data}

ref1 <- read.csv("/omics/groups/OE0436/data/Linh/Datasets/Spatial_transcriptomics/SC ref/GSM5392421_RCC-PR3-PTumor1.count.csv.gz", row.names = 1)
ref2 <- read.csv("/omics/groups/OE0436/data/Linh/Datasets/Spatial_transcriptomics/SC ref/GSM5392422_RCC-PR3-PTumor2.count.csv.gz", row.names = 1)
ref3 <- read.csv("/omics/groups/OE0436/data/Linh/Datasets/Spatial_transcriptomics/SC ref/GSM5392423_RCC-PR3-PTumor3.count.csv.gz", row.names = 1)

ref1 <- CreateSeuratObject(counts = ref1)
ref2 <- CreateSeuratObject(counts = ref2)
ref3 <- CreateSeuratObject(counts = ref3)

```

```{r Import annotation}
sc_anno = read_excel("/omics/groups/OE0436/data/Linh/Datasets/Spatial_transcriptomics/SC ref/Supplementary/41467_2022_33375_MOESM6_ESM.xlsx")
colnames (sc_anno) = c("barcode","celltype1","celltype2","4","5","6","7")

################################## Match barcodes and create new metadata vectors

ref1_barcode <- gsub("\\.", "-", Cells(ref1))

# create annotation vectors to put in seurat objects
matched_annotations <- sc_anno %>% 
  filter(barcode %in% ref1_barcode) %>%
  arrange(match(barcode, ref1_barcode))

# add metadata
ref1 [["celltype1"]] <- matched_annotations$celltype1
ref1 [["celltype2"]] <- matched_annotations$celltype2

# do the same for ref2 and ref3


ref2_barcode <- gsub("\\.", "-", Cells(ref2))

# create annotation vectors to put in seurat objects
matched_annotations <- sc_anno %>% 
  filter(barcode %in% ref2_barcode) %>%
  arrange(match(barcode, ref2_barcode))

# add metadata
ref2 [["celltype1"]] <- matched_annotations$celltype1
ref2 [["celltype2"]] <- matched_annotations$celltype2

ref3_barcode <- gsub("\\.", "-", Cells(ref3))

# create annotation vectors to put in seurat objects
matched_annotations <- sc_anno %>% 
  filter(barcode %in% ref3_barcode) %>%
  arrange(match(barcode, ref3_barcode))

# add metadata
ref3 [["celltype1"]] <- matched_annotations$celltype1
ref3 [["celltype2"]] <- matched_annotations$celltype2

```


```{r SCTransform }
ref = merge(x = ref1, y = list(ref2, ref3))
ref <- JoinLayers(ref)
# attempt with 3000 cells
random_cells = sample(Cells(ref),10000)
ref_sub = ref[,random_cells]
ref_sub <- SCTransform(ref_sub, ncells = 3000, verbose = FALSE)

```


Integration
 [1] "Erythroid"                "Mono-1"                   "CTL-2"                    "Mono-3"                  
 [5] "NK-2"                     "NKT"                      "CTL-1"                    "Mast_cells"              
 [9] "Mono-2"                   "Thelper"                  "CD4 naive"                "Macro"                   
[13] "NK-1"                     "Macro-3"                  "mDC_CD1c"                 "Pericytes1"              
[17] "Tumor"                    "Pericytes2"               "Macro-2"                  "Endothelial-1"           
[21] "mDC_CLEC9A"               "Macro-1"                  "Endothelial-2"            "memBcell"                
[25] "Treg"                     "Proliferation Tcell"      "Mature_B"                 "Proliferation T"         
[29] "Endothelial-4"            "Endothelial-5"            "Fibroblast"               "Fibroblast proliferating"
[33] "Endothelial-3"            "mDC_LAMP3"

 [1] "Erythroid"           "Mono"                "CTL"                 "NK"                  "NKT"            
 [6] "Mast_cells"          "CD4"                 "Macro"               "mDC"                 "Pericytes"       
[11] "Tumor"               "Endothelial"         "memBcell"            "Treg"                "Proliferation Tcell"
[16] "Mature_B"            "Fibroblast"         
sum(ref_sub@meta.data[["celltype2"]] == "Macro-2")
[1] 99
sum(ref_sub@meta.data[["celltype2"]] == "Macro-3")
[1] 87

```{r}

DefaultAssay(c3_obj) <- "SCT"

anchors <- FindTransferAnchors(reference = ref_sub, query = c3_obj, normalization.method = "SCT")
predictions.assay <- TransferData(anchorset = anchors, refdata = ref_sub$celltype1, prediction.assay = TRUE,
    weight.reduction = c3_obj[["pca"]], dims = 1:30)
c3_obj[["predictions"]] <- predictions.assay



DefaultAssay(c3_obj) <- "predictions"
SpatialFeaturePlot(c3_obj,features = c("Macro"),  pt.size.factor = 1.6, ncol = 2, crop = TRUE)

  
```